language: cpp

compiler: gcc

branches:
  # Build only from develop, when develop changes.
  only: develop
    
before_install:
  # Set package repoository.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Update the system.
  - sudo apt-get -qq update
  
  # Get GCC 4.8 (for C++11 support)
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  
install:
  # Get GMP (GNU Multiprecision Arithmetic Library)
  # Get OpenSSL (for test validation only)
  - sudo apt-get -qq install libgmp-dev libssl-dev

  # Install required boost components at the minimum version required.
  - ./boost.sh

script:
  # Build the develop branch and all locally-built dependencies.
  - ./build.sh CFLAGS="-s"
