version: 3.0.0.{build}-{branch}

os:
  - Visual Studio 2013
  
platform:
  - x64
  - Win32

configuration:
  - StaticDebug
  - StaticRelease
  
matrix:
  fast_finish: true
  
skip_tags: true
clone_folder: c:\git\libbitcoin

before_build:
  - mkdir c:\nuget
  - nuget restore c:\git\libbitcoin\builds\msvc\vs2013\libbitcoin.sln -Outputdir c:\nuget
  - powershell c:\git\libbitcoin\prebuild_ctp_install.ps1

build:
  parallel: true
  project: c:\git\libbitcoin\builds\msvc\vs2013\libbitcoin.sln
  
test_script:
  - powershell c:\git\libbitcoin\libbitcoin_test_runner.ps1

